### ISSUE TITLE
[Bug]: Codec issues while trying to read binaries/text files

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/presidio-cli#8]
### What happened?

In some cases, when the CLI tries to differentiate binaries from text, it runs into the following error:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/presidio", line 8, in <module>
    sys.exit(run())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/presidio_cli/cli.py", line 202, in run
    problems = analyze(f, conf, filepath)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/presidio_cli/analyzer.py", line 83, in analyze
    content = input.read()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

This needs to be fixed.

### Version

v0.0.4

### Which version(s) of Python were you using?

3.10

### Relevant log output

```Python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/presidio", line 8, in <module>
    sys.exit(run())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/presidio_cli/cli.py", line 202, in run
    problems = analyze(f, conf, filepath)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/presidio_cli/analyzer.py", line 83, in analyze
    content = input.read()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

https://github.com/insightsengineering/presidio-cli/blob/main/presidio_cli/config.py#L28-L39 is where the implementation exists to determine if the file is a `text` file.

**Comment by walkowif** [comment]
In [this line](https://github.com/insightsengineering/presidio-cli/blob/main/presidio_cli/config.py#L35) we accept a file containing `0x8b` character as a text file. However, a valid UTF-8 string cannot have `0x8b` in any possible place.

There is a StackOverflow question linking to [this document](https://www.rfc-editor.org/rfc/rfc3629#section-3).
The table shows that binary `0xxxxxxx` cannot encode `0x8b`.
`0x8b` has to be encoded with two bytes that have the form of binary `110xxxxx 10xxxxxx`.
`10001011` representing `0x8b` is not a valid first octet of UTF-8 binary sequence.
